# Generated by Django 5.0.7 on 2024-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(error_messages={'required': 'Please Enter your title'}, max_length=100),
        ),
    ]
